# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import evaluations.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FINISHED', 'Finished')], default='CLOSED', max_length=15)),
                ('name', models.CharField(max_length=250)),
                ('special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('FRESH', 'Fresh'), ('GIVEN_OUT', 'Given out'), ('USED', 'Used')], default='FRESH', max_length=10)),
                ('helper', models.BooleanField(default=False)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.Evaluation')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', evaluations.fields.OrderField(blank=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_questions', to='evaluations.Category')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.QuestionSet'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.Semester'),
        ),
        migrations.AddField(
            model_name='category',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.QuestionSet'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('name', 'question_set')]),
        ),
    ]
