sudo: true
before_install:
  - cp env.example oire/settings/.env
language: python
python:
  - "3.4"
install: "pip install -r requirements/development.txt"
script: python manage.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)