from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^questionsets/$',
        views.QuestionSetListView.as_view(),
        name='questionset_list'),
    re_path(r'^questionsets/new/$',
        views.QuestionSetAddView.as_view(),
        name='new_questionset'),
    re_path(r'^questionsets/(?P<pk>\d+)/edit/$',
        views.QuestionSetUpdateView.as_view(),
        name='questionset_edit'),
    re_path(r'^evaluations/$',
        views.EvaluationListView.as_view(),
        name='evaluation_list'),
    re_path(r'^evaluations/new/$',
        views.EvaluationAddView.as_view(),
        name='new_evaluation'),
    re_path(r'^evaluations/(?P<pk>\d+)/edit/$',
        views.EvaluationUpdateView.as_view(),
        name='evaluation_edit'),
    re_path(r'^evaluation/open/(?P<eval>\d+)/$',
        views.EvaluationOpenView.as_view(),
        name='evaluation_open'),
    re_path(r'^evaluation/finish/(?P<eval>\d+)/$',
        views.EvaluationFinishView.as_view(),
        name='evaluation_finish'),
    re_path(r'^evaluation/(?P<eval>\d+)/sections/open/$',
        views.EvaluationOpenAllSectionsView.as_view(),
        name='evaluation_open_all_section'),
    re_path(r'^questions/$',
        views.QuestionListView.as_view(),
        name='question_list'),
    re_path(r'^questions/new/$',
        views.QuestionAddView.as_view(),
        name='new_question'),
    re_path(r'^questions/(?P<pk>\d+)/edit/$',
        views.QuestionUpdateView.as_view(),
        name='question_edit'),
    re_path(r'^categories/new/$',
        views.CategoryAddView.as_view(),
        name='new_category'),
    re_path(r'^categories/(?P<pk>\d+)/edit/$',
        views.CategoryUpdateView.as_view(),
        name='category_edit'),
    re_path(r'^keys/section/(?P<sec>\d+)/$',
        views.KeySectionListView.as_view(),
        name='key_section_list'),

    re_path(r'^evaluate/$',
        views.EvaluateFormView.as_view(),
        name='evaluate'),

]
