# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], default='LOCKED', max_length=15)),
                ('enrolled', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('instructors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('season', 'year')]),
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.Semester'),
        ),
    ]
