# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('instructors', models.TextField()),
                ('enrolled', models.IntegerField()),
                ('semester', models.CharField(max_length=50)),
                ('error_column', models.CharField(max_length=50)),
                ('error_message', models.TextField()),
            ],
        ),
    ]
