# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_presection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presection',
            name='error_column',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='presection',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
