# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_auto_20170212_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presection',
            name='course',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='presection',
            name='crn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='presection',
            name='instructors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='presection',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='presection',
            name='semester',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='presection',
            name='time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
