# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_auto_20170213_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presection',
            name='enrolled',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
